---


- name: set package_base_path
  set_fact:
    package_base_path: "{{ base_path }}/{{ current_package_name }}/{{ current_package_version }}"
    package_startup_script: "{{ launch_daemon_prefix }}.{{ current_package_name }}-{{ current_package_version }}.plist"

- name: set base package variables
  set_fact:
    package_dist_path: "{{ package_base_path }}/dist"
    package_tmp_path: "{{ package_base_path }}/tmp"

- name: call install.yml
  include_tasks: upgrade/install.yml

- name: update state-manager
  include_role:
    name: state-manager
  vars:
    state_action: update_state
    state_package_name: "{{ current_package_name }}"
    state_package_version: "{{ current_package_version }}"


- name: start service via service-manager
  include_role:
    name: service-manager
  vars:
    service_action: start
    service_package_name: "{{ current_package_name }}"
    service_package_version: "{{ current_package_version }}"
