---

- name: "check mysql root password file"
  stat:
    path: "{{ package_data_path }}/password.yml"
  register: mysql_57_root_password_file_obj

- name: Generate password for root user
  shell: "openssl rand -hex 4"
  register: mysql_57_root_password_obj
  when: mysql_57_root_password_file_obj.stat.exists == false

- name: set new root user password
  set_fact:
    mysql_57_root_password: "{{ mysql_57_root_password_obj.stdout }}"
  when: mysql_57_root_password_file_obj.stat.exists == false

- lineinfile:
    path: "{{ package_etc_path }}/password.yml"
    line: 'mysql_57_root_password: "{{ mysql_57_root_password }}"'
    create: yes
  when: mysql_57_root_password_file_obj.stat.exists == false

- name: include password.yml
  include_vars: "{{ package_etc_path }}/password.yml"
  when: mysql_57_root_password_file_obj.stat.exists == true

- name: ensure my.cnf for mysql is up2date
  template:
    src: "my.cnf.j2"
    dest: "{{ package_etc_path }}/my.cnf"
    owner: "{{ package_user }}"
    group: "{{ package_group }}"
    mode: '0644'
  notify: service | mysql-5.7 | restarted

- name: "check mysql data folder"
  stat:
    path: "{{ package_data_path }}/mysql"
  register: mysql_57_current_release_data_path_obj

- name: "run mysql initialize command if data directory is empty"
  command: "bin/mysqld --defaults-file={{ package_etc_path }}/my.cnf --user={{ package_user }} --basedir={{ package_base_path }} --datadir={{ package_data_path }} --initialize-insecure"
  args:
    chdir: "{{ package_dist_path }}"
  when: mysql_57_current_release_data_path_obj.stat.exists == false

- name: "start mysql service"
  command: "launchctl load -w {{ launch_daemons_base_path }}/{{ package_startup_script }}"
  become: true

- name: wait for mysqld to start
  wait_for:
    path: "{{ mysql_57_socket }}"
    state: present

- name: "set new root password"
  command: "bin/mysqladmin --socket={{ mysql_57_socket }} -u root password '{{ mysql_57_root_password }}'"
  args:
    chdir: "{{ package_dist_path }}"
  when: mysql_57_current_release_data_path_obj.stat.exists == false


