---

- name: fail when dnsmasq_domain is not set
  fail:
    msg: "'dnsmasq_domain' var is not set"
  when: dnsmasq_domain is not defined

- name: "delete dnsmasq configuration for domain '{{ dnsmasq_domain }}'"
  file:
    path: "{{ package_etc_path }}/conf.d/{{ dnsmasq_domain }}.conf"
    state: absent

- name: "delete resolver configuration for domain '{{ dnsmasq_domain }}'"
  file:
    path: "/etc/resolver/{{ dnsmasq_domain }}"
    state: absent

- name: start service via service-manager
  include_role:
    name: service-manager
  vars:
    service_action: restart
    service_package_name: "{{ current_package_name }}"
    service_package_version: "{{ current_package_version }}"
