---

# check if sudo password works
- command: "true"
  become: True

- shell: sw_vers -productVersion
  register: sw_vers

# todo: remove hardcoded os_version when introducing distil package-manager
- set_fact:
    #os_version: "{{ sw_vers.stdout }}"
     os_version: "10.13"

#- include_role:
#    name: gnutar