---

- block:
    - name: check defaults state file
      stat:
        path: "{{ defaults_state_file }}"
      register: defaults_state_file_obj

    - name: load defaults state file
      include_vars:
        file: "{{ defaults_state_file }}"
        name: defaults_state
      when: defaults_state_file_obj.stat.exists

    - name: set empty defaults_state object
      set_fact:
        defaults_state: "{{ package_defaults }}"
      when: not defaults_state_file_obj.stat.exists|bool
  when: defaults_state is not defined

- name: "reset 'result' variable"
  set_fact:
    result: false

- name: "check if {{ package_name }}-{{ package_version }} is default version"
  set_fact:
    result: true
  when: defaults_state[package_name] == package_version
