---

- name: "certificate-manager | ensure base directories existing"
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: staff
    mode: '0755'
  with_items:
    - "{{ certificate_base_path }}"
  become: true

# always include ca tasks
- include_tasks: "ca.yml"

- include_tasks: "certificate.yml"
  when: (certificate_action is defined) and (certificate_action == "generate")