---

- name: "ensure package directories existing"
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ package_user }}"
    group: "{{ package_group }}"
    mode: "0755"
  with_items:
    - "{{ package_etc_path }}/conf.d"
    - "{{ package_etc_path }}/servers"

- name: Generate dhparams file
  shell: "openssl dhparam -out {{ package_etc_path }}/{{ nginx_dhparams_file }} {{ nginx_dhparams_keysize }}"
  args:
    creates: "{{ package_etc_path }}/{{ nginx_dhparams_file }}"